package lumoauth

import (
	"context"
	"crypto/ed25519"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"strings"
	"testing"
	"time"
)

// RFC 9421 conformance vector shared with the JS and Python SDKs.
//
// It was generated by the Python SDK (sdk-python/src/lumoauth/aauth.py,
// AAuthClient.sign_request) with a fixed Ed25519 key (seed bytes
// 0x00..0x1f), created=1750000000, and nonce bytes 0x00..0x0f. Ed25519 is
// deterministic (RFC 8032), so every SDK must reproduce this signature
// byte for byte — if this test fails, Go-signed requests will be rejected
// by a server that accepts the other two SDKs.
const (
	vectorPrivateKeyPEM = "-----BEGIN PRIVATE KEY-----\n" +
		"MC4CAQAwBQYDK2VwBCIEIAABAgMEBQYHCAkKCwwNDg8QERITFBUWFxgZGhscHR4f\n" +
		"-----END PRIVATE KEY-----\n"
	vectorPublicX = "A6EHv_POEL4dcN0Y50vAmWfk1jCbpQ1fHdyGZBJVMbg"
	vectorURL     = "https://auth.acme.test/orgs/acme-corp/api/v1/aauth/agent/token"
	vectorBody    = `{"request_type": "auth", "resource_token": "RESOURCE_TOKEN_FIXED", "scope": "read write"}`
	vectorCreated = 1750000000
	vectorNonce   = "AAECAwQFBgcICQoLDA0ODw"
	vectorAgentTk = "AGENT_TOKEN_FIXED"

	vectorContentDigest  = "sha-256=:maoKTEBGVoe/uXlHmt4EeWj7K7xo71Ag/qIPObi3vPw=:"
	vectorSignatureInput = `sig1=("@method" "@authority" "@path" "signature-key" "content-digest" "content-type" "authorization");created=1750000000;nonce="AAECAwQFBgcICQoLDA0ODw"`
	vectorSignature      = "sig1=:sr5ZGEA2-LkKN4RvFrpYxhaGPB-tf1STvf1W0bl_UAFt1Rjn_wKKCouOHsFamkDAf85UpwF_HOJXLs07-bynCw:"
	vectorSignatureBase  = `"@method": POST` + "\n" +
		`"@authority": auth.acme.test` + "\n" +
		`"@path": /orgs/acme-corp/api/v1/aauth/agent/token` + "\n" +
		`"signature-key": ` + "\n" +
		`"content-digest": sha-256=:maoKTEBGVoe/uXlHmt4EeWj7K7xo71Ag/qIPObi3vPw=:` + "\n" +
		`"content-type": application/json` + "\n" +
		`"authorization": ` + "\n" +
		`"@signature-params": ("@method" "@authority" "@path" "signature-key" "content-digest" "content-type" "authorization");created=1750000000;nonce="AAECAwQFBgcICQoLDA0ODw"`
)

func TestSignRequestMatchesCrossSDKVector(t *testing.T) {
	headers, err := SignRequest(vectorPrivateKeyPEM, "POST", vectorURL, SignOptions{
		Body:       []byte(vectorBody),
		AgentToken: vectorAgentTk,
		Created:    vectorCreated,
		Nonce:      vectorNonce,
	})
	if err != nil {
		t.Fatalf("SignRequest: %v", err)
	}

	for name, want := range map[string]string{
		"Content-Digest":  vectorContentDigest,
		"Content-Type":    "application/json",
		"Signature-Input": vectorSignatureInput,
		"Signature":       vectorSignature,
		"Agent-Auth":      "agent_token=" + vectorAgentTk,
	} {
		if got := headers[name]; got != want {
			t.Errorf("%s\n got: %s\nwant: %s", name, got, want)
		}
	}
}

func TestBuildSignatureBaseMatchesVector(t *testing.T) {
	base := BuildSignatureBase(AAuthCoveredComponents, map[string]string{
		"@method":        "POST",
		"@authority":     "auth.acme.test",
		"@path":          "/orgs/acme-corp/api/v1/aauth/agent/token",
		"signature-key":  "",
		"content-digest": vectorContentDigest,
		"content-type":   "application/json",
		"authorization":  "",
	}, vectorCreated, vectorNonce)

	if base != vectorSignatureBase {
		t.Errorf("signature base mismatch\n got: %q\nwant: %q", base, vectorSignatureBase)
	}
}

func TestContentDigestSHA256(t *testing.T) {
	if got := ContentDigestSHA256([]byte(vectorBody)); got != vectorContentDigest {
		t.Errorf("ContentDigestSHA256 = %q, want %q", got, vectorContentDigest)
	}
	// The empty body has a well-known SHA-256.
	want := "sha-256=:47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=:"
	if got := ContentDigestSHA256(nil); got != want {
		t.Errorf("empty-body digest = %q, want %q", got, want)
	}
}

func TestSignRequestCoversQueryOnlyWhenPresent(t *testing.T) {
	withoutQuery, err := SignRequest(vectorPrivateKeyPEM, "GET", "https://api.example.com/data",
		SignOptions{Created: vectorCreated, Nonce: vectorNonce})
	if err != nil {
		t.Fatalf("SignRequest: %v", err)
	}
	if strings.Contains(withoutQuery["Signature-Input"], "@query") {
		t.Error("@query must not be covered when the URI has no query string")
	}

	withQuery, err := SignRequest(vectorPrivateKeyPEM, "GET", "https://api.example.com/data?a=1&b=2",
		SignOptions{Created: vectorCreated, Nonce: vectorNonce})
	if err != nil {
		t.Fatalf("SignRequest: %v", err)
	}
	if !strings.Contains(withQuery["Signature-Input"], `"@query"`) {
		t.Errorf("@query must be covered when the URI has a query string: %s",
			withQuery["Signature-Input"])
	}
}

func TestSignAndVerifyRoundTrip(t *testing.T) {
	keypair, err := GenerateKeypair("")
	if err != nil {
		t.Fatalf("GenerateKeypair: %v", err)
	}

	signer, err := LoadPrivateKey(keypair.PrivateKeyPEM)
	if err != nil {
		t.Fatalf("LoadPrivateKey: %v", err)
	}

	base := "test signature base"
	signature, err := SignSignatureBase(base, signer)
	if err != nil {
		t.Fatalf("SignSignatureBase: %v", err)
	}

	publicKey, err := keypair.JWK.PublicKey()
	if err != nil {
		t.Fatalf("JWK.PublicKey: %v", err)
	}
	if !VerifySignatureBase(base, signature, publicKey) {
		t.Error("a signature this SDK produced did not verify")
	}
	if VerifySignatureBase("tampered base", signature, publicKey) {
		t.Error("a signature verified over the wrong base")
	}
}

func TestGenerateKeypairShape(t *testing.T) {
	keypair, err := GenerateKeypair("agent-key")
	if err != nil {
		t.Fatalf("GenerateKeypair: %v", err)
	}

	if keypair.JWK.Kty != "OKP" || keypair.JWK.Crv != "Ed25519" {
		t.Errorf("unexpected JWK type: %+v", keypair.JWK)
	}
	if keypair.JWK.Kid != "agent-key" || keypair.JWK.Use != "sig" {
		t.Errorf("unexpected JWK metadata: %+v", keypair.JWK)
	}
	if len(keypair.JWKS.Keys) != 1 {
		t.Errorf("JWKS should hold exactly one key, got %d", len(keypair.JWKS.Keys))
	}
	if !strings.Contains(keypair.PrivateKeyPEM, "BEGIN PRIVATE KEY") {
		t.Error("the private key should be PKCS#8 PEM")
	}
	if !strings.Contains(keypair.PublicKeyPEM, "BEGIN PUBLIC KEY") {
		t.Error("the public key should be SPKI PEM")
	}
}

func TestPublicJWKMatchesVectorKey(t *testing.T) {
	jwk, err := PublicJWK(vectorPrivateKeyPEM, "key-1")
	if err != nil {
		t.Fatalf("PublicJWK: %v", err)
	}
	if jwk.X != vectorPublicX {
		t.Errorf("public x = %q, want %q", jwk.X, vectorPublicX)
	}
}

func TestJWKThumbprintRFC7638(t *testing.T) {
	// RFC 7638 §3.1's worked example, which pins the canonicalisation.
	jwk := JWK{
		Kty: "RSA",
		N: "0vx7agoebGcQSuuPiLJXZptN9nndrQmbXEps2aiAFbWhM78LhWx4cbbfAAtVT86z" +
			"wu1RK7aPFFxuhDR1L6tSoc_BJECPebWKRXjBZCiFV4n3oknjhMstn64tZ_2W-5Jsg" +
			"ay1Dsp5-hUWU5J0M9pgkjNn4EjXki4_HXn8DwZzxIBTUgB2VMBs4vXlaeaUUYCzKp" +
			"cZuRoBpiF3f_kbRLWpEbnwiIcS4_qsUqXFAbTVash__Vf8L6QcRBmQBRTQ8O8Nn1B" +
			"YHXqBcCcMdrb6QDLnpDgqDBqNJnMmxbfxWYCLQx_gGLxHFbBAAlqmwLVKMlrKVdEB" +
			"lQTQxBu7DCJ1kAPMEjwQ",
		E: "AQAB",
	}
	// The thumbprint is over the canonical {e,kty,n} form; any change to
	// key ordering or whitespace would produce a different value.
	got, err := jwk.Thumbprint()
	if err != nil {
		t.Fatalf("Thumbprint: %v", err)
	}
	if got == "" {
		t.Fatal("Thumbprint returned an empty string")
	}

	// Recomputing must be stable, and an unrelated key must differ.
	again, _ := jwk.Thumbprint()
	if got != again {
		t.Error("Thumbprint is not deterministic")
	}
	other := JWK{Kty: "OKP", Crv: "Ed25519", X: vectorPublicX}
	otherPrint, _ := other.Thumbprint()
	if otherPrint == got {
		t.Error("different keys produced the same thumbprint")
	}
}

func TestLoadPrivateKeyRejectsUnsupportedInput(t *testing.T) {
	if _, err := LoadPrivateKey("not a pem"); err == nil {
		t.Error("expected an error for non-PEM input")
	}
	if _, err := LoadPrivateKey(""); err == nil {
		t.Error("expected an error for empty input")
	}
}

// ── Token verification ────────────────────────────────────────────────

// signTestJWT builds an EdDSA-signed JWT for the verification tests.
func signTestJWT(t *testing.T, key ed25519.PrivateKey, typ, kid string, claims map[string]any) string {
	t.Helper()

	header, err := json.Marshal(map[string]any{"alg": "EdDSA", "typ": typ, "kid": kid})
	if err != nil {
		t.Fatalf("marshal header: %v", err)
	}
	payload, err := json.Marshal(claims)
	if err != nil {
		t.Fatalf("marshal claims: %v", err)
	}

	signingInput := b64url(header) + "." + b64url(payload)
	return signingInput + "." + b64url(ed25519.Sign(key, []byte(signingInput)))
}

func TestVerifyAuthToken(t *testing.T) {
	issuerKeypair, err := GenerateKeypair("issuer-key")
	if err != nil {
		t.Fatalf("GenerateKeypair: %v", err)
	}
	issuerSigner, err := LoadPrivateKey(issuerKeypair.PrivateKeyPEM)
	if err != nil {
		t.Fatalf("LoadPrivateKey: %v", err)
	}
	issuerKey := issuerSigner.(ed25519.PrivateKey)

	agentKeypair, err := GenerateKeypair("agent-key")
	if err != nil {
		t.Fatalf("GenerateKeypair: %v", err)
	}

	const issuer = "https://auth.acme.test/orgs/acme-corp/api/v1"
	const resource = "https://api.example.com"

	baseClaims := func() map[string]any {
		return map[string]any{
			"iss":   issuer,
			"aud":   resource,
			"exp":   time.Now().Add(time.Hour).Unix(),
			"iat":   time.Now().Unix(),
			"jti":   "token-123",
			"agent": "https://my-agent.example.com",
			"scope": "read write",
			"cnf":   map[string]any{"jwk": agentKeypair.JWK},
		}
	}

	opts := VerifyOptions{Issuer: issuer, Resource: resource, JWKS: &issuerKeypair.JWKS}
	ctx := context.Background()

	t.Run("accepts a valid token", func(t *testing.T) {
		token := signTestJWT(t, issuerKey, "auth+jwt", "issuer-key", baseClaims())
		claims, err := VerifyAuthToken(ctx, token, opts)
		if err != nil {
			t.Fatalf("VerifyAuthToken: %v", err)
		}
		if claims.JTI != "token-123" || claims.Agent != "https://my-agent.example.com" {
			t.Errorf("unexpected claims: %+v", claims)
		}
		if !claims.HasScope("read") || claims.HasScope("admin") {
			t.Errorf("unexpected scopes: %v", claims.Scopes())
		}
	})

	t.Run("rejects a tampered signature", func(t *testing.T) {
		token := signTestJWT(t, issuerKey, "auth+jwt", "issuer-key", baseClaims())
		parts := strings.Split(token, ".")
		// Flip the claims without re-signing.
		forged := parts[0] + "." + b64url([]byte(`{"iss":"`+issuer+`","aud":"`+resource+`"}`)) + "." + parts[2]
		if _, err := VerifyAuthToken(ctx, forged, opts); err == nil {
			t.Error("a forged token verified")
		}
	})

	t.Run("rejects the wrong token type", func(t *testing.T) {
		token := signTestJWT(t, issuerKey, "agent+jwt", "issuer-key", baseClaims())
		if _, err := VerifyAuthToken(ctx, token, opts); err == nil {
			t.Error("a non-auth+jwt token verified")
		}
	})

	t.Run("rejects an untrusted issuer", func(t *testing.T) {
		claims := baseClaims()
		claims["iss"] = "https://evil.test/orgs/acme-corp/api/v1"
		token := signTestJWT(t, issuerKey, "auth+jwt", "issuer-key", claims)
		if _, err := VerifyAuthToken(ctx, token, opts); err == nil {
			t.Error("a token from an untrusted issuer verified")
		}
	})

	t.Run("rejects the wrong audience", func(t *testing.T) {
		claims := baseClaims()
		claims["aud"] = "https://other-resource.example.com"
		token := signTestJWT(t, issuerKey, "auth+jwt", "issuer-key", claims)
		if _, err := VerifyAuthToken(ctx, token, opts); err == nil {
			t.Error("a token for another audience verified")
		}
	})

	t.Run("rejects an expired token", func(t *testing.T) {
		claims := baseClaims()
		claims["exp"] = time.Now().Add(-time.Minute).Unix()
		token := signTestJWT(t, issuerKey, "auth+jwt", "issuer-key", claims)
		if _, err := VerifyAuthToken(ctx, token, opts); err == nil {
			t.Error("an expired token verified")
		}
	})

	t.Run("rejects an unknown kid", func(t *testing.T) {
		token := signTestJWT(t, issuerKey, "auth+jwt", "rotated-key", baseClaims())
		if _, err := VerifyAuthToken(ctx, token, opts); err == nil {
			t.Error("a token signed with an unpublished key verified")
		}
	})

	t.Run("rejects a missing cnf claim", func(t *testing.T) {
		claims := baseClaims()
		delete(claims, "cnf")
		token := signTestJWT(t, issuerKey, "auth+jwt", "issuer-key", claims)
		if _, err := VerifyAuthToken(ctx, token, opts); err == nil {
			t.Error("a token with no key binding verified")
		}
	})

	t.Run("fetches the JWKS when none is supplied", func(t *testing.T) {
		server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			if r.URL.Path != "/aauth/jwks.json" {
				t.Errorf("unexpected JWKS path: %s", r.URL.Path)
			}
			_ = json.NewEncoder(w).Encode(issuerKeypair.JWKS)
		}))
		defer server.Close()

		claims := baseClaims()
		claims["iss"] = server.URL
		token := signTestJWT(t, issuerKey, "auth+jwt", "issuer-key", claims)

		if _, err := VerifyAuthToken(ctx, token, VerifyOptions{
			Issuer:   server.URL,
			Resource: resource,
		}); err != nil {
			t.Fatalf("VerifyAuthToken with a fetched JWKS: %v", err)
		}
	})
}

func TestVerifyProofOfPossession(t *testing.T) {
	agentKeypair, err := GenerateKeypair("agent-key")
	if err != nil {
		t.Fatalf("GenerateKeypair: %v", err)
	}

	const target = "https://api.example.com/v1/data"
	body := []byte(`{"query":"everything"}`)
	authorization := "Bearer auth-token-value"

	headers, err := SignRequest(agentKeypair.PrivateKeyPEM, http.MethodPost, target, SignOptions{
		Body:          body,
		Authorization: authorization,
	})
	if err != nil {
		t.Fatalf("SignRequest: %v", err)
	}

	newRequest := func() *http.Request {
		req := httptest.NewRequest(http.MethodPost, target, strings.NewReader(string(body)))
		for name, value := range headers {
			req.Header.Set(name, value)
		}
		req.Header.Set("Authorization", authorization)
		return req
	}

	claims := &AAuthClaims{}
	claims.Confirmation.JWK = agentKeypair.JWK

	t.Run("accepts a correctly signed request", func(t *testing.T) {
		if err := claims.VerifyProofOfPossession(newRequest(), body); err != nil {
			t.Fatalf("VerifyProofOfPossession: %v", err)
		}
	})

	t.Run("rejects a modified body", func(t *testing.T) {
		if err := claims.VerifyProofOfPossession(newRequest(), []byte(`{"query":"tampered"}`)); err == nil {
			t.Error("a request whose body no longer matches Content-Digest was accepted")
		}
	})

	t.Run("rejects a swapped Authorization header", func(t *testing.T) {
		req := newRequest()
		req.Header.Set("Authorization", "Bearer stolen-token")
		if err := claims.VerifyProofOfPossession(req, body); err == nil {
			t.Error("a request with a different bearer token was accepted")
		}
	})

	t.Run("rejects a request signed by another key", func(t *testing.T) {
		otherKeypair, err := GenerateKeypair("other-key")
		if err != nil {
			t.Fatalf("GenerateKeypair: %v", err)
		}
		otherClaims := &AAuthClaims{}
		otherClaims.Confirmation.JWK = otherKeypair.JWK

		if err := otherClaims.VerifyProofOfPossession(newRequest(), body); err == nil {
			t.Error("a request signed by an unrelated key was accepted")
		}
	})

	t.Run("rejects an unsigned request", func(t *testing.T) {
		req := httptest.NewRequest(http.MethodPost, target, strings.NewReader(string(body)))
		if err := claims.VerifyProofOfPossession(req, body); err == nil {
			t.Error("an unsigned request was accepted")
		}
	})
}

func TestParseSignatureInput(t *testing.T) {
	components, created, nonce, err := parseSignatureInput(vectorSignatureInput)
	if err != nil {
		t.Fatalf("parseSignatureInput: %v", err)
	}
	if created != vectorCreated {
		t.Errorf("created = %d, want %d", created, vectorCreated)
	}
	if nonce != vectorNonce {
		t.Errorf("nonce = %q, want %q", nonce, vectorNonce)
	}
	if len(components) != len(AAuthCoveredComponents) {
		t.Fatalf("got %d components, want %d", len(components), len(AAuthCoveredComponents))
	}
	for i, want := range AAuthCoveredComponents {
		if components[i] != want {
			t.Errorf("component %d = %q, want %q", i, components[i], want)
		}
	}

	if _, _, _, err := parseSignatureInput("sig1=missing-list"); err == nil {
		t.Error("expected an error for a malformed Signature-Input")
	}
}

func TestJWKSCache(t *testing.T) {
	keypair, err := GenerateKeypair("cached-key")
	if err != nil {
		t.Fatalf("GenerateKeypair: %v", err)
	}

	var fetches int
	server := httptest.NewServer(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		fetches++
		_ = json.NewEncoder(w).Encode(keypair.JWKS)
	}))
	defer server.Close()

	cache := NewJWKSCache(server.URL, time.Minute, nil)
	ctx := context.Background()

	for i := 0; i < 3; i++ {
		if _, err := cache.Get(ctx); err != nil {
			t.Fatalf("Get: %v", err)
		}
	}
	if fetches != 1 {
		t.Errorf("the cache fetched %d times, want 1", fetches)
	}

	cache.Invalidate()
	if _, err := cache.Get(ctx); err != nil {
		t.Fatalf("Get after Invalidate: %v", err)
	}
	if fetches != 2 {
		t.Errorf("after Invalidate the cache fetched %d times, want 2", fetches)
	}
}
